/*
    1. Constructors must have the same name of the class
    2. Constructors do not have a return type
    3. Constructors must be place at public area of the class
    4. Default construct does not have any parameters
    5. If not created any constructor a defult one is generated by C++ compiler with defualts
    6. Default constructor is invoked when an object is created

    After crated a constructor the default constructor generated by c++ compiler is lost


*/




#include <iostream>
using namespace std;

class User {
public:
    string FirstName;
    string LastName;
    int Age;
    string Email;

    //User(){} // empty constructor

    User() { // default constructor
        FirstName = "No first name";
        LastName = "No last name";
        Age = 0;
        Email = "Email not set";
    }

    User(string fName, string lName, int age) { // parameterized constructor
        FirstName = fName;
        LastName = lName;
        Age = age;
        Email = fName + "." + lName + "@email.com";
    }
};

void GetUserInfo(User user) {
    cout << "_______________________________________________________\n";
    cout << "First name: " << user.FirstName << endl;
    cout << "Last name: " << user.LastName << endl;
    cout << "Age: " << user.Age << endl;
    cout << "Email: " << user.Email << endl;
    cout << "_______________________________________________________\n\n";
}

int main()
{
 
    // thats is the trivial way to work with a class with a default constructor of the class
    /*
    User user1;
    user1.FirstName = "Marcelo";
    user1.LastName = "Moraes";
    user1.Age = 52;
    user1.Email = "marcelo.moraes@email.com";

    User user2;
    user2.FirstName = "Anna";
    user2.LastName = "Lopez";
    user2.Age = 33;
    user2.Email = "anna.lopez@email.com";

    cout << "First name: " << user1.FirstName << endl;
    cout << "Last name: "  << user1.LastName  << endl;
    cout << "Age: "        << user1.Age       << endl;
    cout << "Email: "      << user1.Email     << endl;
    cout << "---------------------------\n\n";

    cout << "First name: " << user2.FirstName << endl;
    cout << "Last name: "  << user2.LastName  << endl;
    cout << "Age: "        << user2.Age       << endl;
    cout << "Email: "      << user2.Email     << endl;
    cout << "---------------------------\n\n";
    */

    User user1("Anna", "Lopez", 22);// using parameterized constructor
    User user2("Marcelo", "Moraes", 52);
    User user3; // using default constructor

    GetUserInfo(user1);
    GetUserInfo(user2);
    GetUserInfo(user3);




    cin.get();
    return 0;

}
